# Generated by Django 5.2.8 on 2025-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cours_chapitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='debutant', max_length=15),
        ),
    ]
